name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed ExperimentalFMSynth.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ExperimentalFMSynth
          path: |
            dist/*

  upload:
    name: Create release and upload artifacts
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.event_name == 'push'  # Do not run on pull requests
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            ( cd ExperimentalFMSynth ; zip -r ExperimentalFMSynth.app.zip ExperimentalFMSynth.app )
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage --appimage-extract-and-run **/ExperimentalFMSynth.exe **/ExperimentalFMSynth.app.zip **/ExperimentalFMSynth
